from __future__ import annotations

MARKET_PRESETS: dict[str, list[dict[str, str]]] = {
    "EQUITIES": [
        {"label": "S&P 500", "symbol": "^GSPC"},
        {"label": "NASDAQ", "symbol": "^IXIC"},
        {"label": "DOW JONES", "symbol": "^DJI"},
        {"label": "RUSSELL 2000", "symbol": "^RUT"},
        {"label": "VIX", "symbol": "^VIX"},
        {"label": "DOLLAR DXY", "symbol": "DX-Y.NYB"},
        {"label": "FTSE 100", "symbol": "^FTSE"},
        {"label": "DAX", "symbol": "^GDAXI"},
        {"label": "NIKKEI 225", "symbol": "^N225"},
        {"label": "HANG SENG", "symbol": "^HSI"},
    ],
    "FX": [
        {"label": "EUR/USD", "symbol": "EURUSD=X"},
        {"label": "GBP/USD", "symbol": "GBPUSD=X"},
        {"label": "USD/JPY", "symbol": "JPY=X"},
        {"label": "USD/CHF", "symbol": "CHF=X"},
        {"label": "USD/CAD", "symbol": "CAD=X"},
        {"label": "AUD/USD", "symbol": "AUDUSD=X"},
    ],
    "COMMODITIES": [
        {"label": "GOLD", "symbol": "GC=F"},
        {"label": "SILVER", "symbol": "SI=F"},
        {"label": "CRUDE OIL WTI", "symbol": "CL=F"},
        {"label": "BRENT OIL", "symbol": "BZ=F"},
        {"label": "NATURAL GAS", "symbol": "NG=F"},
        {"label": "COPPER", "symbol": "HG=F"},
    ],
    "FIXED_INCOME": [
        {"label": "US 10Y YIELD", "symbol": "^TNX"},
        {"label": "US 5Y YIELD", "symbol": "^FVX"},
        {"label": "US 30Y YIELD", "symbol": "^TYX"},
        {"label": "US 13W BILL", "symbol": "^IRX"},
    ],
    "CRYPTO": [
        {"label": "BITCOIN", "symbol": "BTC-USD"},
        {"label": "ETHEREUM", "symbol": "ETH-USD"},
        {"label": "SOLANA", "symbol": "SOL-USD"},
        {"label": "BNB", "symbol": "BNB-USD"},
        {"label": "XRP", "symbol": "XRP-USD"},
        {"label": "DOGECOIN", "symbol": "DOGE-USD"},
    ],
}

MARKET_LABELS: dict[str, str] = {
    item["symbol"]: item["label"] for values in MARKET_PRESETS.values() for item in values
}

MARKET_SYMBOL_UNIVERSE: dict[str, list[str]] = {
    "US:NASDAQ": ["AAPL", "MSFT", "NVDA", "TSLA", "META", "GOOGL", "AMZN", "NFLX"],
    "US:NYSE": ["JPM", "UNH", "XOM", "V", "MA", "JNJ", "WMT", "BAC"],
    "ID:IDX": ["BBCA.JK", "BBRI.JK", "BMRI.JK", "TLKM.JK", "ASII.JK", "UNTR.JK"],
    "JP:TSE": ["7203.T", "6758.T", "9984.T", "8306.T"],
    "GB:LSE": ["HSBA.L", "BP.L", "AZN.L", "ULVR.L"],
    "HK:HKEX": ["0700.HK", "9988.HK", "0005.HK", "0939.HK"],
}

POPULAR_SEARCH_SYMBOLS: set[str] = {
    "AAPL",
    "MSFT",
    "NVDA",
    "TSLA",
    "BBCA.JK",
    "BBRI.JK",
    "SPY",
    "QQQ",
    "BTC-USD",
    "ETH-USD",
}

MARKET_SEARCH_UNIVERSE: list[dict[str, str]] = [
    {"symbol": "AAPL", "name": "Apple Inc", "exchange": "NASDAQ", "type": "EQUITY", "market": "US"},
    {
        "symbol": "MSFT",
        "name": "Microsoft Corporation",
        "exchange": "NASDAQ",
        "type": "EQUITY",
        "market": "US",
    },
    {
        "symbol": "NVDA",
        "name": "NVIDIA Corporation",
        "exchange": "NASDAQ",
        "type": "EQUITY",
        "market": "US",
    },
    {
        "symbol": "GOOGL",
        "name": "Alphabet Inc Class A",
        "exchange": "NASDAQ",
        "type": "EQUITY",
        "market": "US",
    },
    {
        "symbol": "GOOG",
        "name": "Alphabet Inc Class C",
        "exchange": "NASDAQ",
        "type": "EQUITY",
        "market": "US",
    },
    {
        "symbol": "AMZN",
        "name": "Amazon.com Inc",
        "exchange": "NASDAQ",
        "type": "EQUITY",
        "market": "US",
    },
    {
        "symbol": "META",
        "name": "Meta Platforms Inc",
        "exchange": "NASDAQ",
        "type": "EQUITY",
        "market": "US",
    },
    {"symbol": "TSLA", "name": "Tesla Inc", "exchange": "NASDAQ", "type": "EQUITY", "market": "US"},
    {
        "symbol": "AVGO",
        "name": "Broadcom Inc",
        "exchange": "NASDAQ",
        "type": "EQUITY",
        "market": "US",
    },
    {
        "symbol": "NFLX",
        "name": "Netflix Inc",
        "exchange": "NASDAQ",
        "type": "EQUITY",
        "market": "US",
    },
    {
        "symbol": "AMD",
        "name": "Advanced Micro Devices Inc",
        "exchange": "NASDAQ",
        "type": "EQUITY",
        "market": "US",
    },
    {
        "symbol": "INTC",
        "name": "Intel Corporation",
        "exchange": "NASDAQ",
        "type": "EQUITY",
        "market": "US",
    },
    {
        "symbol": "QCOM",
        "name": "Qualcomm Inc",
        "exchange": "NASDAQ",
        "type": "EQUITY",
        "market": "US",
    },
    {
        "symbol": "CSCO",
        "name": "Cisco Systems Inc",
        "exchange": "NASDAQ",
        "type": "EQUITY",
        "market": "US",
    },
    {"symbol": "ADBE", "name": "Adobe Inc", "exchange": "NASDAQ", "type": "EQUITY", "market": "US"},
    {
        "symbol": "CRM",
        "name": "Salesforce Inc",
        "exchange": "NYSE",
        "type": "EQUITY",
        "market": "US",
    },
    {
        "symbol": "ORCL",
        "name": "Oracle Corporation",
        "exchange": "NYSE",
        "type": "EQUITY",
        "market": "US",
    },
    {
        "symbol": "IBM",
        "name": "International Business Machines Corporation",
        "exchange": "NYSE",
        "type": "EQUITY",
        "market": "US",
    },
    {
        "symbol": "JPM",
        "name": "JPMorgan Chase & Co",
        "exchange": "NYSE",
        "type": "EQUITY",
        "market": "US",
    },
    {
        "symbol": "BAC",
        "name": "Bank of America Corporation",
        "exchange": "NYSE",
        "type": "EQUITY",
        "market": "US",
    },
    {
        "symbol": "WFC",
        "name": "Wells Fargo & Company",
        "exchange": "NYSE",
        "type": "EQUITY",
        "market": "US",
    },
    {
        "symbol": "GS",
        "name": "Goldman Sachs Group Inc",
        "exchange": "NYSE",
        "type": "EQUITY",
        "market": "US",
    },
    {
        "symbol": "MS",
        "name": "Morgan Stanley",
        "exchange": "NYSE",
        "type": "EQUITY",
        "market": "US",
    },
    {"symbol": "V", "name": "Visa Inc", "exchange": "NYSE", "type": "EQUITY", "market": "US"},
    {
        "symbol": "MA",
        "name": "Mastercard Incorporated",
        "exchange": "NYSE",
        "type": "EQUITY",
        "market": "US",
    },
    {
        "symbol": "PYPL",
        "name": "PayPal Holdings Inc",
        "exchange": "NASDAQ",
        "type": "EQUITY",
        "market": "US",
    },
    {
        "symbol": "SCHW",
        "name": "Charles Schwab Corporation",
        "exchange": "NYSE",
        "type": "EQUITY",
        "market": "US",
    },
    {
        "symbol": "BLK",
        "name": "BlackRock Inc",
        "exchange": "NYSE",
        "type": "EQUITY",
        "market": "US",
    },
    {"symbol": "C", "name": "Citigroup Inc", "exchange": "NYSE", "type": "EQUITY", "market": "US"},
    {
        "symbol": "AXP",
        "name": "American Express Company",
        "exchange": "NYSE",
        "type": "EQUITY",
        "market": "US",
    },
    {
        "symbol": "UNH",
        "name": "UnitedHealth Group Incorporated",
        "exchange": "NYSE",
        "type": "EQUITY",
        "market": "US",
    },
    {
        "symbol": "LLY",
        "name": "Eli Lilly and Company",
        "exchange": "NYSE",
        "type": "EQUITY",
        "market": "US",
    },
    {
        "symbol": "JNJ",
        "name": "Johnson & Johnson",
        "exchange": "NYSE",
        "type": "EQUITY",
        "market": "US",
    },
    {"symbol": "PFE", "name": "Pfizer Inc", "exchange": "NYSE", "type": "EQUITY", "market": "US"},
    {
        "symbol": "MRK",
        "name": "Merck & Co Inc",
        "exchange": "NYSE",
        "type": "EQUITY",
        "market": "US",
    },
    {"symbol": "ABBV", "name": "AbbVie Inc", "exchange": "NYSE", "type": "EQUITY", "market": "US"},
    {
        "symbol": "TMO",
        "name": "Thermo Fisher Scientific Inc",
        "exchange": "NYSE",
        "type": "EQUITY",
        "market": "US",
    },
    {
        "symbol": "ABT",
        "name": "Abbott Laboratories",
        "exchange": "NYSE",
        "type": "EQUITY",
        "market": "US",
    },
    {
        "symbol": "DHR",
        "name": "Danaher Corporation",
        "exchange": "NYSE",
        "type": "EQUITY",
        "market": "US",
    },
    {
        "symbol": "XOM",
        "name": "Exxon Mobil Corporation",
        "exchange": "NYSE",
        "type": "EQUITY",
        "market": "US",
    },
    {
        "symbol": "CVX",
        "name": "Chevron Corporation",
        "exchange": "NYSE",
        "type": "EQUITY",
        "market": "US",
    },
    {
        "symbol": "COP",
        "name": "ConocoPhillips",
        "exchange": "NYSE",
        "type": "EQUITY",
        "market": "US",
    },
    {
        "symbol": "SLB",
        "name": "Schlumberger Limited",
        "exchange": "NYSE",
        "type": "EQUITY",
        "market": "US",
    },
    {
        "symbol": "CAT",
        "name": "Caterpillar Inc",
        "exchange": "NYSE",
        "type": "EQUITY",
        "market": "US",
    },
    {
        "symbol": "BA",
        "name": "Boeing Company",
        "exchange": "NYSE",
        "type": "EQUITY",
        "market": "US",
    },
    {"symbol": "GE", "name": "GE Aerospace", "exchange": "NYSE", "type": "EQUITY", "market": "US"},
    {
        "symbol": "HON",
        "name": "Honeywell International Inc",
        "exchange": "NASDAQ",
        "type": "EQUITY",
        "market": "US",
    },
    {
        "symbol": "UPS",
        "name": "United Parcel Service Inc",
        "exchange": "NYSE",
        "type": "EQUITY",
        "market": "US",
    },
    {
        "symbol": "DE",
        "name": "Deere & Company",
        "exchange": "NYSE",
        "type": "EQUITY",
        "market": "US",
    },
    {"symbol": "WMT", "name": "Walmart Inc", "exchange": "NYSE", "type": "EQUITY", "market": "US"},
    {
        "symbol": "COST",
        "name": "Costco Wholesale Corporation",
        "exchange": "NASDAQ",
        "type": "EQUITY",
        "market": "US",
    },
    {
        "symbol": "HD",
        "name": "Home Depot Inc",
        "exchange": "NYSE",
        "type": "EQUITY",
        "market": "US",
    },
    {
        "symbol": "MCD",
        "name": "McDonald's Corporation",
        "exchange": "NYSE",
        "type": "EQUITY",
        "market": "US",
    },
    {"symbol": "NKE", "name": "NIKE Inc", "exchange": "NYSE", "type": "EQUITY", "market": "US"},
    {
        "symbol": "KO",
        "name": "Coca-Cola Company",
        "exchange": "NYSE",
        "type": "EQUITY",
        "market": "US",
    },
    {
        "symbol": "PEP",
        "name": "PepsiCo Inc",
        "exchange": "NASDAQ",
        "type": "EQUITY",
        "market": "US",
    },
    {
        "symbol": "SBUX",
        "name": "Starbucks Corporation",
        "exchange": "NASDAQ",
        "type": "EQUITY",
        "market": "US",
    },
    {
        "symbol": "DIS",
        "name": "Walt Disney Company",
        "exchange": "NYSE",
        "type": "EQUITY",
        "market": "US",
    },
    {
        "symbol": "TGT",
        "name": "Target Corporation",
        "exchange": "NYSE",
        "type": "EQUITY",
        "market": "US",
    },
    {
        "symbol": "SPY",
        "name": "SPDR S&P 500 ETF Trust",
        "exchange": "NYSEARCA",
        "type": "ETF",
        "market": "US",
    },
    {
        "symbol": "QQQ",
        "name": "Invesco QQQ Trust",
        "exchange": "NASDAQ",
        "type": "ETF",
        "market": "US",
    },
    {
        "symbol": "IWM",
        "name": "iShares Russell 2000 ETF",
        "exchange": "NYSEARCA",
        "type": "ETF",
        "market": "US",
    },
    {
        "symbol": "DIA",
        "name": "SPDR Dow Jones Industrial Average ETF Trust",
        "exchange": "NYSEARCA",
        "type": "ETF",
        "market": "US",
    },
    {
        "symbol": "VTI",
        "name": "Vanguard Total Stock Market ETF",
        "exchange": "NYSEARCA",
        "type": "ETF",
        "market": "US",
    },
    {
        "symbol": "VOO",
        "name": "Vanguard S&P 500 ETF",
        "exchange": "NYSEARCA",
        "type": "ETF",
        "market": "US",
    },
    {
        "symbol": "IVV",
        "name": "iShares Core S&P 500 ETF",
        "exchange": "NYSEARCA",
        "type": "ETF",
        "market": "US",
    },
    {
        "symbol": "XLK",
        "name": "Technology Select Sector SPDR Fund",
        "exchange": "NYSEARCA",
        "type": "ETF",
        "market": "US",
    },
    {
        "symbol": "XLF",
        "name": "Financial Select Sector SPDR Fund",
        "exchange": "NYSEARCA",
        "type": "ETF",
        "market": "US",
    },
    {
        "symbol": "XLE",
        "name": "Energy Select Sector SPDR Fund",
        "exchange": "NYSEARCA",
        "type": "ETF",
        "market": "US",
    },
    {
        "symbol": "XLY",
        "name": "Consumer Discretionary Select Sector SPDR Fund",
        "exchange": "NYSEARCA",
        "type": "ETF",
        "market": "US",
    },
    {
        "symbol": "XLP",
        "name": "Consumer Staples Select Sector SPDR Fund",
        "exchange": "NYSEARCA",
        "type": "ETF",
        "market": "US",
    },
    {
        "symbol": "GLD",
        "name": "SPDR Gold Shares",
        "exchange": "NYSEARCA",
        "type": "ETF",
        "market": "US",
    },
    {
        "symbol": "SLV",
        "name": "iShares Silver Trust",
        "exchange": "NYSEARCA",
        "type": "ETF",
        "market": "US",
    },
    {
        "symbol": "TLT",
        "name": "iShares 20+ Year Treasury Bond ETF",
        "exchange": "NASDAQ",
        "type": "ETF",
        "market": "US",
    },
    {
        "symbol": "HYG",
        "name": "iShares iBoxx High Yield Corporate Bond ETF",
        "exchange": "NYSEARCA",
        "type": "ETF",
        "market": "US",
    },
    {
        "symbol": "ARKK",
        "name": "ARK Innovation ETF",
        "exchange": "NYSEARCA",
        "type": "ETF",
        "market": "US",
    },
    {
        "symbol": "^GSPC",
        "name": "S&P 500 Index",
        "exchange": "SNP",
        "type": "INDEX",
        "market": "US",
    },
    {
        "symbol": "^IXIC",
        "name": "NASDAQ Composite",
        "exchange": "NASDAQ",
        "type": "INDEX",
        "market": "US",
    },
    {
        "symbol": "^DJI",
        "name": "Dow Jones Industrial Average",
        "exchange": "DJI",
        "type": "INDEX",
        "market": "US",
    },
    {
        "symbol": "^RUT",
        "name": "Russell 2000 Index",
        "exchange": "RUSSELL",
        "type": "INDEX",
        "market": "US",
    },
    {
        "symbol": "^VIX",
        "name": "CBOE Volatility Index",
        "exchange": "CBOE",
        "type": "INDEX",
        "market": "US",
    },
    {
        "symbol": "^FTSE",
        "name": "FTSE 100 Index",
        "exchange": "FTSE",
        "type": "INDEX",
        "market": "GB",
    },
    {
        "symbol": "^GDAXI",
        "name": "DAX Performance Index",
        "exchange": "XETRA",
        "type": "INDEX",
        "market": "DE",
    },
    {
        "symbol": "^N225",
        "name": "Nikkei 225 Index",
        "exchange": "NIKKEI",
        "type": "INDEX",
        "market": "JP",
    },
    {
        "symbol": "^HSI",
        "name": "Hang Seng Index",
        "exchange": "HKEX",
        "type": "INDEX",
        "market": "HK",
    },
    {
        "symbol": "^STOXX50E",
        "name": "EURO STOXX 50 Index",
        "exchange": "STOXX",
        "type": "INDEX",
        "market": "EU",
    },
    {
        "symbol": "^TNX",
        "name": "US 10 Year Treasury Yield",
        "exchange": "CBOE",
        "type": "INDEX",
        "market": "US",
    },
    {
        "symbol": "DX-Y.NYB",
        "name": "US Dollar Index",
        "exchange": "NYBOT",
        "type": "INDEX",
        "market": "US",
    },
    {
        "symbol": "^JKSE",
        "name": "Jakarta Composite Index",
        "exchange": "IDX",
        "type": "INDEX",
        "market": "ID",
    },
    {
        "symbol": "BBCA.JK",
        "name": "Bank Central Asia Tbk PT",
        "exchange": "IDX",
        "type": "EQUITY",
        "market": "ID",
    },
    {
        "symbol": "BBRI.JK",
        "name": "Bank Rakyat Indonesia Persero Tbk PT",
        "exchange": "IDX",
        "type": "EQUITY",
        "market": "ID",
    },
    {
        "symbol": "BMRI.JK",
        "name": "Bank Mandiri Persero Tbk PT",
        "exchange": "IDX",
        "type": "EQUITY",
        "market": "ID",
    },
    {
        "symbol": "BBNI.JK",
        "name": "Bank Negara Indonesia Persero Tbk PT",
        "exchange": "IDX",
        "type": "EQUITY",
        "market": "ID",
    },
    {
        "symbol": "BBTN.JK",
        "name": "Bank Tabungan Negara Persero Tbk PT",
        "exchange": "IDX",
        "type": "EQUITY",
        "market": "ID",
    },
    {
        "symbol": "BRIS.JK",
        "name": "Bank Syariah Indonesia Tbk PT",
        "exchange": "IDX",
        "type": "EQUITY",
        "market": "ID",
    },
    {
        "symbol": "PNBN.JK",
        "name": "Bank Pan Indonesia Tbk PT",
        "exchange": "IDX",
        "type": "EQUITY",
        "market": "ID",
    },
    {
        "symbol": "BNGA.JK",
        "name": "Bank CIMB Niaga Tbk PT",
        "exchange": "IDX",
        "type": "EQUITY",
        "market": "ID",
    },
    {
        "symbol": "NISP.JK",
        "name": "Bank OCBC NISP Tbk PT",
        "exchange": "IDX",
        "type": "EQUITY",
        "market": "ID",
    },
    {
        "symbol": "TLKM.JK",
        "name": "Telkom Indonesia Persero Tbk PT",
        "exchange": "IDX",
        "type": "EQUITY",
        "market": "ID",
    },
    {
        "symbol": "ASII.JK",
        "name": "Astra International Tbk PT",
        "exchange": "IDX",
        "type": "EQUITY",
        "market": "ID",
    },
    {
        "symbol": "UNTR.JK",
        "name": "United Tractors Tbk PT",
        "exchange": "IDX",
        "type": "EQUITY",
        "market": "ID",
    },
    {
        "symbol": "UNVR.JK",
        "name": "Unilever Indonesia Tbk PT",
        "exchange": "IDX",
        "type": "EQUITY",
        "market": "ID",
    },
    {
        "symbol": "GOTO.JK",
        "name": "GoTo Gojek Tokopedia Tbk PT",
        "exchange": "IDX",
        "type": "EQUITY",
        "market": "ID",
    },
    {
        "symbol": "AMMN.JK",
        "name": "Amman Mineral Internasional Tbk PT",
        "exchange": "IDX",
        "type": "EQUITY",
        "market": "ID",
    },
    {
        "symbol": "BREN.JK",
        "name": "Barito Renewables Energy Tbk PT",
        "exchange": "IDX",
        "type": "EQUITY",
        "market": "ID",
    },
    {
        "symbol": "TPIA.JK",
        "name": "Chandra Asri Pacific Tbk PT",
        "exchange": "IDX",
        "type": "EQUITY",
        "market": "ID",
    },
    {
        "symbol": "DSSA.JK",
        "name": "Dian Swastatika Sentosa Tbk PT",
        "exchange": "IDX",
        "type": "EQUITY",
        "market": "ID",
    },
    {
        "symbol": "BYAN.JK",
        "name": "Bayan Resources Tbk PT",
        "exchange": "IDX",
        "type": "EQUITY",
        "market": "ID",
    },
    {
        "symbol": "ANTM.JK",
        "name": "Aneka Tambang Tbk PT",
        "exchange": "IDX",
        "type": "EQUITY",
        "market": "ID",
    },
    {
        "symbol": "INCO.JK",
        "name": "Vale Indonesia Tbk PT",
        "exchange": "IDX",
        "type": "EQUITY",
        "market": "ID",
    },
    {
        "symbol": "MDKA.JK",
        "name": "Merdeka Copper Gold Tbk PT",
        "exchange": "IDX",
        "type": "EQUITY",
        "market": "ID",
    },
    {
        "symbol": "MEDC.JK",
        "name": "Medco Energi Internasional Tbk PT",
        "exchange": "IDX",
        "type": "EQUITY",
        "market": "ID",
    },
    {
        "symbol": "ADRO.JK",
        "name": "Alamtri Resources Indonesia Tbk PT",
        "exchange": "IDX",
        "type": "EQUITY",
        "market": "ID",
    },
    {
        "symbol": "ITMG.JK",
        "name": "Indo Tambangraya Megah Tbk PT",
        "exchange": "IDX",
        "type": "EQUITY",
        "market": "ID",
    },
    {
        "symbol": "PTBA.JK",
        "name": "Bukit Asam Tbk PT",
        "exchange": "IDX",
        "type": "EQUITY",
        "market": "ID",
    },
    {
        "symbol": "HRUM.JK",
        "name": "Harum Energy Tbk PT",
        "exchange": "IDX",
        "type": "EQUITY",
        "market": "ID",
    },
    {
        "symbol": "PGAS.JK",
        "name": "Perusahaan Gas Negara Tbk PT",
        "exchange": "IDX",
        "type": "EQUITY",
        "market": "ID",
    },
    {
        "symbol": "AKRA.JK",
        "name": "AKR Corporindo Tbk PT",
        "exchange": "IDX",
        "type": "EQUITY",
        "market": "ID",
    },
    {
        "symbol": "ICBP.JK",
        "name": "Indofood CBP Sukses Makmur Tbk PT",
        "exchange": "IDX",
        "type": "EQUITY",
        "market": "ID",
    },
    {
        "symbol": "INDF.JK",
        "name": "Indofood Sukses Makmur Tbk PT",
        "exchange": "IDX",
        "type": "EQUITY",
        "market": "ID",
    },
    {
        "symbol": "MYOR.JK",
        "name": "Mayora Indah Tbk PT",
        "exchange": "IDX",
        "type": "EQUITY",
        "market": "ID",
    },
    {
        "symbol": "KLBF.JK",
        "name": "Kalbe Farma Tbk PT",
        "exchange": "IDX",
        "type": "EQUITY",
        "market": "ID",
    },
    {
        "symbol": "SIDO.JK",
        "name": "Industri Jamu dan Farmasi Sido Muncul Tbk PT",
        "exchange": "IDX",
        "type": "EQUITY",
        "market": "ID",
    },
    {
        "symbol": "SMGR.JK",
        "name": "Semen Indonesia Persero Tbk PT",
        "exchange": "IDX",
        "type": "EQUITY",
        "market": "ID",
    },
    {
        "symbol": "INTP.JK",
        "name": "Indocement Tunggal Prakarsa Tbk PT",
        "exchange": "IDX",
        "type": "EQUITY",
        "market": "ID",
    },
    {
        "symbol": "BSDE.JK",
        "name": "Bumi Serpong Damai Tbk PT",
        "exchange": "IDX",
        "type": "EQUITY",
        "market": "ID",
    },
    {
        "symbol": "CTRA.JK",
        "name": "Ciputra Development Tbk PT",
        "exchange": "IDX",
        "type": "EQUITY",
        "market": "ID",
    },
    {
        "symbol": "EXCL.JK",
        "name": "XL Axiata Tbk PT",
        "exchange": "IDX",
        "type": "EQUITY",
        "market": "ID",
    },
    {
        "symbol": "ISAT.JK",
        "name": "Indosat Tbk PT",
        "exchange": "IDX",
        "type": "EQUITY",
        "market": "ID",
    },
    {"symbol": "EURUSD=X", "name": "EUR/USD", "exchange": "FX", "type": "FX", "market": "FX"},
    {"symbol": "GBPUSD=X", "name": "GBP/USD", "exchange": "FX", "type": "FX", "market": "FX"},
    {"symbol": "JPY=X", "name": "USD/JPY", "exchange": "FX", "type": "FX", "market": "FX"},
    {"symbol": "CHF=X", "name": "USD/CHF", "exchange": "FX", "type": "FX", "market": "FX"},
    {"symbol": "CAD=X", "name": "USD/CAD", "exchange": "FX", "type": "FX", "market": "FX"},
    {"symbol": "AUDUSD=X", "name": "AUD/USD", "exchange": "FX", "type": "FX", "market": "FX"},
    {"symbol": "NZDUSD=X", "name": "NZD/USD", "exchange": "FX", "type": "FX", "market": "FX"},
    {"symbol": "EURJPY=X", "name": "EUR/JPY", "exchange": "FX", "type": "FX", "market": "FX"},
    {"symbol": "GBPJPY=X", "name": "GBP/JPY", "exchange": "FX", "type": "FX", "market": "FX"},
    {"symbol": "EURGBP=X", "name": "EUR/GBP", "exchange": "FX", "type": "FX", "market": "FX"},
    {
        "symbol": "GC=F",
        "name": "Gold Futures",
        "exchange": "COMEX",
        "type": "FUTURE",
        "market": "US",
    },
    {
        "symbol": "SI=F",
        "name": "Silver Futures",
        "exchange": "COMEX",
        "type": "FUTURE",
        "market": "US",
    },
    {
        "symbol": "CL=F",
        "name": "Crude Oil WTI Futures",
        "exchange": "NYMEX",
        "type": "FUTURE",
        "market": "US",
    },
    {
        "symbol": "BZ=F",
        "name": "Brent Crude Oil Futures",
        "exchange": "NYMEX",
        "type": "FUTURE",
        "market": "US",
    },
    {
        "symbol": "NG=F",
        "name": "Natural Gas Futures",
        "exchange": "NYMEX",
        "type": "FUTURE",
        "market": "US",
    },
    {
        "symbol": "HG=F",
        "name": "Copper Futures",
        "exchange": "COMEX",
        "type": "FUTURE",
        "market": "US",
    },
    {
        "symbol": "ZC=F",
        "name": "Corn Futures",
        "exchange": "CBOT",
        "type": "FUTURE",
        "market": "US",
    },
    {
        "symbol": "ZS=F",
        "name": "Soybean Futures",
        "exchange": "CBOT",
        "type": "FUTURE",
        "market": "US",
    },
    {
        "symbol": "ZW=F",
        "name": "Wheat Futures",
        "exchange": "CBOT",
        "type": "FUTURE",
        "market": "US",
    },
    {
        "symbol": "ES=F",
        "name": "E-mini S&P 500 Futures",
        "exchange": "CME",
        "type": "FUTURE",
        "market": "US",
    },
    {
        "symbol": "NQ=F",
        "name": "E-mini NASDAQ 100 Futures",
        "exchange": "CME",
        "type": "FUTURE",
        "market": "US",
    },
    {
        "symbol": "BTC-USD",
        "name": "Bitcoin USD",
        "exchange": "CCC",
        "type": "CRYPTO",
        "market": "CRYPTO",
    },
    {
        "symbol": "ETH-USD",
        "name": "Ethereum USD",
        "exchange": "CCC",
        "type": "CRYPTO",
        "market": "CRYPTO",
    },
    {
        "symbol": "SOL-USD",
        "name": "Solana USD",
        "exchange": "CCC",
        "type": "CRYPTO",
        "market": "CRYPTO",
    },
    {
        "symbol": "BNB-USD",
        "name": "BNB USD",
        "exchange": "CCC",
        "type": "CRYPTO",
        "market": "CRYPTO",
    },
    {
        "symbol": "XRP-USD",
        "name": "XRP USD",
        "exchange": "CCC",
        "type": "CRYPTO",
        "market": "CRYPTO",
    },
    {
        "symbol": "DOGE-USD",
        "name": "Dogecoin USD",
        "exchange": "CCC",
        "type": "CRYPTO",
        "market": "CRYPTO",
    },
    {
        "symbol": "ADA-USD",
        "name": "Cardano USD",
        "exchange": "CCC",
        "type": "CRYPTO",
        "market": "CRYPTO",
    },
    {
        "symbol": "AVAX-USD",
        "name": "Avalanche USD",
        "exchange": "CCC",
        "type": "CRYPTO",
        "market": "CRYPTO",
    },
    {
        "symbol": "LINK-USD",
        "name": "Chainlink USD",
        "exchange": "CCC",
        "type": "CRYPTO",
        "market": "CRYPTO",
    },
    {
        "symbol": "DOT-USD",
        "name": "Polkadot USD",
        "exchange": "CCC",
        "type": "CRYPTO",
        "market": "CRYPTO",
    },
    {
        "symbol": "0700.HK",
        "name": "Tencent Holdings Limited",
        "exchange": "HKEX",
        "type": "EQUITY",
        "market": "HK",
    },
    {
        "symbol": "9988.HK",
        "name": "Alibaba Group Holding Limited",
        "exchange": "HKEX",
        "type": "EQUITY",
        "market": "HK",
    },
    {
        "symbol": "0005.HK",
        "name": "HSBC Holdings plc",
        "exchange": "HKEX",
        "type": "EQUITY",
        "market": "HK",
    },
    {
        "symbol": "7203.T",
        "name": "Toyota Motor Corporation",
        "exchange": "TSE",
        "type": "EQUITY",
        "market": "JP",
    },
    {
        "symbol": "6758.T",
        "name": "Sony Group Corporation",
        "exchange": "TSE",
        "type": "EQUITY",
        "market": "JP",
    },
    {
        "symbol": "9984.T",
        "name": "SoftBank Group Corp",
        "exchange": "TSE",
        "type": "EQUITY",
        "market": "JP",
    },
]
MARKET_EXCHANGE_PRESETS: list[dict[str, str]] = [
    {"country": "United States", "country_code": "US", "exchange": "NASDAQ", "suffix": ""},
    {"country": "United States", "country_code": "US", "exchange": "NYSE", "suffix": ""},
    {"country": "Indonesia", "country_code": "ID", "exchange": "IDX", "suffix": ".JK"},
    {"country": "Japan", "country_code": "JP", "exchange": "TSE", "suffix": ".T"},
    {"country": "United Kingdom", "country_code": "GB", "exchange": "LSE", "suffix": ".L"},
    {"country": "Germany", "country_code": "DE", "exchange": "XETRA", "suffix": ".DE"},
    {"country": "France", "country_code": "FR", "exchange": "Euronext Paris", "suffix": ".PA"},
    {"country": "Hong Kong", "country_code": "HK", "exchange": "HKEX", "suffix": ".HK"},
    {"country": "Singapore", "country_code": "SG", "exchange": "SGX", "suffix": ".SI"},
    {"country": "Australia", "country_code": "AU", "exchange": "ASX", "suffix": ".AX"},
    {"country": "Canada", "country_code": "CA", "exchange": "TSX", "suffix": ".TO"},
]

_COUNTRY_ALIASES = {
    "UNITED STATES": "US",
    "USA": "US",
    "US": "US",
    "INDONESIA": "ID",
    "ID": "ID",
    "JAPAN": "JP",
    "JP": "JP",
    "UNITED KINGDOM": "GB",
    "UK": "GB",
    "GB": "GB",
    "GERMANY": "DE",
    "DE": "DE",
    "FRANCE": "FR",
    "FR": "FR",
    "HONG KONG": "HK",
    "HK": "HK",
    "SINGAPORE": "SG",
    "SG": "SG",
    "AUSTRALIA": "AU",
    "AU": "AU",
    "CANADA": "CA",
    "CA": "CA",
}


def normalize_country(country: str) -> str:
    normalized = str(country or "").strip().upper()
    return _COUNTRY_ALIASES.get(normalized, normalized)


def normalize_exchange(exchange: str) -> str:
    return str(exchange or "").strip()


def universe_key(country: str, exchange: str) -> str:
    return f"{normalize_country(country)}:{normalize_exchange(exchange).upper()}"


def get_symbol_universe(country: str, exchange: str) -> list[str]:
    return list(
        MARKET_SYMBOL_UNIVERSE.get(
            universe_key(country, exchange), MARKET_SYMBOL_UNIVERSE["US:NASDAQ"]
        )
    )


def get_exchange_preset(country: str, exchange: str) -> dict[str, str] | None:
    normalized_country = normalize_country(country)
    normalized_exchange = normalize_exchange(exchange).upper()
    for preset in MARKET_EXCHANGE_PRESETS:
        if (
            preset["country_code"] == normalized_country
            and preset["exchange"].upper() == normalized_exchange
        ):
            return dict(preset)
    return None
