from __future__ import annotations

REPORT_DISCLAIMER = (
    "This analysis report does not constitute financial advice, investment advice, trading advice, "
    "or a recommendation to buy, sell, hold, or otherwise transact in any security, stock, asset, "
    "or financial instrument.\n\n"
    "This report is generated by an automated AI-assisted analysis engine using available market "
    "data, provider data, calculated metrics, model output, and configured assumptions at the time "
    "the analysis is created. Because the report is produced through automated processing, it may "
    "contain errors, inaccuracies, outdated information, incomplete data, calculation mistakes, "
    "misinterpretations, or conclusions that do not reflect the latest market conditions.\n\n"
    "All prices, trade levels, risk estimates, volatility estimates, confidence scores, ratings, "
    "summaries, projections, and narrative explanations should be independently checked before "
    "being used. Market conditions can change quickly, and external factors such as company news, "
    "economic data, liquidity, regulation, data provider issues, and unexpected events may materially "
    "affect the accuracy and relevance of the report.\n\n"
    "All investment and trading decisions are the sole responsibility of the user. Financial markets "
    "involve risk, including the possible loss of part or all invested capital. Past performance does "
    "not guarantee future results. Users should review their own financial condition, risk tolerance, "
    "investment objectives, portfolio exposure, and time horizon, and should consult a qualified "
    "financial professional before making any financial decision."
)
