from typing import Annotated, Optional, Any
from typing_extensions import TypedDict
from langgraph.graph import MessagesState


class InvestDebateState(TypedDict):
    stage: Annotated[str, "Current investment debate stage"]
    next_speaker: Annotated[str, "Next debate node to run"]
    consensus_reached: Annotated[bool, "Whether the debate reached early consensus"]
    last_consensus_signal: Annotated[bool, "Whether the latest speaker signaled consensus"]
    bull_confidence: Annotated[float, "Latest bull confidence"]
    bear_confidence: Annotated[float, "Latest bear confidence"]
    bull_history: Annotated[str, "Bullish conversation history"]
    bear_history: Annotated[str, "Bearish conversation history"]
    history: Annotated[str, "Conversation history"]
    current_response: Annotated[str, "Latest response"]
    judge_decision: Annotated[str, "Final judge decision"]
    count: Annotated[int, "Length of the current conversation"]


class RiskDebateState(TypedDict):
    stage: Annotated[str, "Current risk debate stage"]
    next_speaker: Annotated[str, "Next risk debate node to run"]
    consensus_reached: Annotated[bool, "Whether the risk debate reached early consensus"]
    last_consensus_signal: Annotated[bool, "Whether the latest speaker signaled consensus"]
    aggressive_confidence: Annotated[float, "Latest aggressive confidence"]
    conservative_confidence: Annotated[float, "Latest conservative confidence"]
    neutral_confidence: Annotated[float, "Latest neutral confidence"]
    aggressive_history: Annotated[str, "Aggressive agent conversation history"]
    conservative_history: Annotated[str, "Conservative agent conversation history"]
    neutral_history: Annotated[str, "Neutral agent conversation history"]
    history: Annotated[str, "Conversation history"]
    latest_speaker: Annotated[str, "Analyst that spoke last"]
    current_aggressive_response: Annotated[str, "Latest response by the aggressive analyst"]
    current_conservative_response: Annotated[str, "Latest response by the conservative analyst"]
    current_neutral_response: Annotated[str, "Latest response by the neutral analyst"]
    judge_decision: Annotated[str, "Judge's decision"]
    count: Annotated[int, "Length of the current conversation"]


class AgentState(MessagesState):
    company_of_interest: Annotated[str, "Company that we are interested in trading"]
    trade_date: Annotated[str, "What date we are trading at"]
    sender: Annotated[str, "Agent that sent this message"]
    market_report: Annotated[str, "Report from the Market Analyst"]
    sentiment_report: Annotated[str, "Report from the Social Media Analyst"]
    news_report: Annotated[str, "Report from the News Researcher of current world affairs"]
    fundamentals_report: Annotated[str, "Report from the Fundamentals Researcher"]
    investment_debate_state: Annotated[InvestDebateState, "Current state of the investment debate"]
    investment_plan: Annotated[str, "Plan generated by the Research Manager"]
    trader_investment_plan: Annotated[str, "Plan generated by the Trader"]
    risk_debate_state: Annotated[RiskDebateState, "Current state of risk debate"]
    final_trade_decision: Annotated[str, "Final decision made by the Portfolio Manager"]
    past_context: Annotated[str, "Memory log context injected at run start"]
    portfolio_decision: Annotated[Optional[Any], "Typed PortfolioDecision from the Portfolio Manager"]
